sudo: false
language: python
matrix:
  include:
    - os: linux
      python: 2.6
      env: TOX_ENV=py26
    - os: linux
      python: 2.7
      env: TOX_ENV=py27
    - os: linux
      python: 3.3
      env: TOX_ENV=py33
    - os: linux
      python: 3.4
      env: TOX_ENV=py34
    - os: linux
      python: pypy
      env: TOX_ENV=pypy
install:
  - pip install tox
script: tox -e $TOX_ENV
