environment:
    PYTHON: "C:\\Python35"
    PATH: "C:\\Python35;C:\\Python35\\Scripts;%PATH%"
install:
    - python -m ensurepip
    - pip install tox
build_script:
    - python --version
test_script:
    - tox -e py35
